version: '3'

services:
  database:
    container_name: db
    image: mysql:8.0.29

  backend:
    container_name: api
    build:
      context: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/app/src
    tty: true
    stdin_open: true
    command: bash
    depends_on:
      - database

  frontend:
    container_name: app
    build: 
      context: ./frontend
    ports:
      - 5555:5555
    volumes:
      - ./frontend/src:/app/src
    tty: true
    stdin_open: true
    command: bash
    depends_on:
      - backend